### ISSUE TITLE
请问xgboost4j-spark-0.72-online-with-dependencies.jar是怎么编译成的呢？

### ISSUE THREAD

**Issue by jimmy-walker** [Skycrab/xgboost4j-spark#1]
感谢您的分享，请问jar文件夹下的online-with-dependencies.jar是怎么编译生成的呢？我用0.80官网的版本进行编译，没有得到with-dependencies.jar的jar包。

**Comment by Skycrab** [comment]
这个需要修改下pom，用shade打个依赖包。
或者在网上找他人已经打好的包，如https://jar-download.com/artifacts/ml.dmlc/xgboost4j-spark/0.72/source-code

**Comment by Skycrab** [comment]
不过这两个包就是这个项目打的，你可以看下pom
<finalName>xgboost4j-spark-${xgboost.version}-${activatedProperties}-with-dependencies</finalName>

**Comment by jimmy-walker** [comment]
谢谢你
